### ISSUE TITLE
その他のページ img タグ修正

### ISSUE THREAD

**Issue by Reputeless** [Siv3D/Reference-JP#5]

**Comment by Reputeless** [comment]
https://github.com/Siv3D/Reference-JP/wiki/%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB

**Comment by azaika** [comment]
統一という意味では修正したほうが良いかもしれませんが、このページはtableになっているおかげか、もともとレイアウト崩れが発生していないので、むしろ自動のままにしておいたほうが良いのではないですか？

**Comment by Reputeless** [comment]
そうですね、このままにします。他のページも大方直したので close します。
